#ifndef __COMMON_PHY_DEFINE__
#define __COMMON_PHY_DEFINE__

/* 通用信道下标定义 */
#define VBAR_BOARD_CHANNEL_USBHID_INDEX      (0)
#define VBAR_BOARD_CHANNEL_USBKBW_INDEX      (1)
#define VBAR_BOARD_CHANNEL_WIEGAND0_INDEX    (0)
#define VBAR_BOARD_CHANNEL_WIEGAND1_INDEX    (1)
#define VBAR_BOARD_CHANNEL_WIEGAND2_INDEX    (2)
#define VBAR_BOARD_CHANNEL_WIEGAND3_INDEX    (3)
#define VBAR_BOARD_CHANNEL_UART0_INDEX       (0)
#define VBAR_BOARD_CHANNEL_UART1_INDEX       (1)
#define VBAR_BOARD_CHANNEL_UART2_INDEX       (2)
#define VBAR_BOARD_CHANNEL_UART3_INDEX       (3)
#define VBAR_BOARD_CHANNEL_UART4_INDEX       (4)
#define VBAR_BOARD_CHANNEL_UART5_INDEX       (5)
#define VBAR_BOARD_CHANNEL_UART6_INDEX       (6)
#define VBAR_BOARD_CHANNEL_UART7_INDEX       (7)
#define VBAR_BOARD_CHANNEL_UART8_INDEX       (8)
#define VBAR_BOARD_CHANNEL_UART9_INDEX       (9)

#endif
