LOCAL_LIBRARY_VERSION := 1.1.1q
LOCAL_ABS_PATH := $(call my-abs-dir)

LOCAL_LIBRARY_FILES := \
	file:$(LOCAL_ABS_PATH)/lib/libcrypto.so.1.1:$(BUILD_VBAR_SYSTEM_USRLIB_APATH)/libcrypto.so.1.1 \
	link:libcrypto.so.1.1:$(BUILD_VBAR_SYSTEM_USRLIB_APATH)/libcrypto.so \
	file:$(LOCAL_ABS_PATH)/lib/libssl.so.1.1:$(BUILD_VBAR_SYSTEM_USRLIB_APATH)/libssl.so.1.1 \
	link:libssl.so.1.1:$(BUILD_VBAR_SYSTEM_USRLIB_APATH)/libssl.so \
	dir-f:$(LOCAL_ABS_PATH)/etc/ssl:$(BUILD_VBAR_SYSTEM_ROOT_APATH)/etc/ssl \
	dir-l:$(LOCAL_ABS_PATH)/include/openssl:$(BUILD_VBAR_BUILD_INC_THIRDLIB_APATH)/openssl

ifeq ($(CONFIG_VBAR_OPENSSL_SUPPORT)-$(CONFIG_VBAR_OPENSSL_VERSION), y-$(LOCAL_LIBRARY_VERSION))
BUILD_VBAR_COPY_LIST := $(BUILD_VBAR_COPY_LIST) $(LOCAL_LIBRARY_FILES)
BUILD_VBAR_CLEAN_LIST := $(BUILD_VBAR_CLEAN_LIST) $(LOCAL_LIBRARY_FILES)
EXTRALIBS := $(EXTRALIBS) -lssl -lcrypto
else
BUILD_VBAR_CLEAN_LIST := $(BUILD_VBAR_CLEAN_LIST) $(LOCAL_LIBRARY_FILES)
endif

