LOCAL_LIBRARY_VERSION := 1.3.12
LOCAL_ABS_PATH := $(call my-abs-dir)

LOCAL_PAHO_MQTT_LIB_NAME := paho-mqtt3a

ifeq ($(CONFIG_VBAR_MOD_VGMQTT_SSL_SUPPORT), y)
LOCAL_PAHO_MQTT_LIB_NAME := paho-mqtt3as
endif

LOCAL_COPY_LIST := \
	file:$(LOCAL_ABS_PATH)/lib/lib$(LOCAL_PAHO_MQTT_LIB_NAME).so.$(LOCAL_LIBRARY_VERSION):$(BUILD_VBAR_SYSTEM_USRLIB_APATH)/lib$(LOCAL_PAHO_MQTT_LIB_NAME).so.$(LOCAL_LIBRARY_VERSION) \
	link:lib$(LOCAL_PAHO_MQTT_LIB_NAME).so.$(LOCAL_LIBRARY_VERSION):$(BUILD_VBAR_SYSTEM_USRLIB_APATH)/lib$(LOCAL_PAHO_MQTT_LIB_NAME).so.1 \
	link:lib$(LOCAL_PAHO_MQTT_LIB_NAME).so.$(LOCAL_LIBRARY_VERSION):$(BUILD_VBAR_SYSTEM_USRLIB_APATH)/lib$(LOCAL_PAHO_MQTT_LIB_NAME).so \
	dir-l:$(LOCAL_ABS_PATH)/include:$(BUILD_VBAR_BUILD_INC_THIRDLIB_APATH)/mqtt


ifeq ($(CONFIG_VBAR_MQTT_SUPPORT)-$(CONFIG_VBAR_MQTT_VERSION), y-$(LOCAL_LIBRARY_VERSION))
BUILD_VBAR_COPY_LIST := $(BUILD_VBAR_COPY_LIST) $(LOCAL_COPY_LIST)
BUILD_VBAR_CLEAN_LIST := $(BUILD_VBAR_CLEAN_LIST) $(LOCAL_COPY_LIST)
EXTRALIBS := $(EXTRALIBS) -l$(LOCAL_PAHO_MQTT_LIB_NAME)
else
BUILD_VBAR_CLEAN_LIST := $(BUILD_VBAR_CLEAN_LIST) $(LOCAL_COPY_LIST)
endif

